apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform-dev
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: github.com/SantiagoLemoMayoral/bank-AURORA-GLOBAL-DEFENSE
    targetRevision: main
    path: gitops/environments/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true