apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform-staging
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://github.com/SantiagoLemoMayoral/bank.git
    targetRevision: main
    path: gitops/environments/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true