apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: platform
  namespace: argocd

spec:
  sourceRepos:
    - github.com/SantiagoLemoMayoral/bank-AURORA-GLOBAL-DEFENSE

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc

    - namespace: staging
      server: https://kubernetes.default.svc

    - namespace: prod
      server: https://kubernetes.default.svc